// apps/web-vue/src/components/AdminInsights.vue
<script setup lang="ts">
import type { AdminLead } from "@lumadock/api-client";
import { Empty as AEmpty } from "ant-design-vue";
import VChart from "vue-echarts";
import "echarts";
import { computed } from "vue";

import {
  buildDailyLeadCounts,
  buildFinishLeadCounts,
  buildProductLeadCounts,
} from "../lib/adminInsights";

const props = defineProps<{
  leads: AdminLead[];
}>();

const chartColors = ["#16a3a3", "#f15a4a", "#525ddc", "#a4c639"];
const productCounts = computed(() => buildProductLeadCounts(props.leads));
const finishCounts = computed(() => buildFinishLeadCounts(props.leads));
const dailyCounts = computed(() => buildDailyLeadCounts(props.leads));

const productOption = computed(() => ({
  color: chartColors,
  grid: { bottom: 34, left: 36, right: 12, top: 12 },
  series: [
    {
      barMaxWidth: 38,
      data: productCounts.value.map((item) => item.value),
      type: "bar",
    },
  ],
  tooltip: {},
  xAxis: {
    data: productCounts.value.map((item) => item.name),
    type: "category",
  },
  yAxis: { minInterval: 1, type: "value" },
}));

const dailyOption = computed(() => ({
  color: ["#525ddc"],
  grid: { bottom: 34, left: 36, right: 12, top: 12 },
  series: [
    {
      data: dailyCounts.value.map((item) => item.leads),
      smooth: true,
      type: "line",
    },
  ],
  tooltip: {},
  xAxis: { data: dailyCounts.value.map((item) => item.date), type: "category" },
  yAxis: { minInterval: 1, type: "value" },
}));

const finishOption = computed(() => ({
  color: chartColors,
  series: [
    {
      data: finishCounts.value,
      innerRadius: "58%",
      radius: ["48%", "78%"],
      type: "pie",
    },
  ],
  tooltip: {},
}));
</script>

<template>
  <div v-if="!leads.length" class="insight-empty">
    <AEmpty description="No lead insights yet" />
  </div>

  <div v-else class="insight-grid" aria-label="Lead insights">
    <section class="insight-panel">
      <span class="eyebrow">Products</span>
      <h3>Lead mix</h3>
      <VChart
        :option="productOption"
        style="width: 100%; height: 220px"
        autoresize
      />
    </section>

    <section class="insight-panel">
      <span class="eyebrow">Timeline</span>
      <h3>Daily leads</h3>
      <VChart
        :option="dailyOption"
        style="width: 100%; height: 220px"
        autoresize
      />
    </section>

    <section class="insight-panel">
      <span class="eyebrow">Configuration</span>
      <h3>Finish demand</h3>
      <VChart
        :option="finishOption"
        style="width: 100%; height: 220px"
        autoresize
      />
    </section>
  </div>
</template>

// apps/web/src/components/AdminInsights.tsx
import type { AdminLead } from "@lumadock/api-client";
import { Empty } from "antd";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Line,
  LineChart,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import {
  buildDailyLeadCounts,
  buildFinishLeadCounts,
  buildProductLeadCounts,
} from "../lib/adminInsights";

type AdminInsightsProps = {
  leads: AdminLead[];
};

const chartColors = ["#16a3a3", "#f15a4a", "#525ddc", "#a4c639"];

export function AdminInsights({ leads }: AdminInsightsProps) {
  const productCounts = buildProductLeadCounts(leads);
  const finishCounts = buildFinishLeadCounts(leads);
  const dailyCounts = buildDailyLeadCounts(leads);

  if (!leads.length) {
    return (
      <div className="insight-empty">
        <Empty description="No lead insights yet" />
      </div>
    );
  }

  return (
    <div className="insight-grid" aria-label="Lead insights">
      <section className="insight-panel">
        <span className="eyebrow">Products</span>
        <h3>Lead mix</h3>
        <ResponsiveContainer width="100%" height={220}>
          <BarChart data={productCounts}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} />
            <XAxis dataKey="name" tick={{ fontSize: 11 }} />
            <YAxis allowDecimals={false} width={28} />
            <Tooltip />
            <Bar dataKey="value" radius={[6, 6, 0, 0]}>
              {productCounts.map((entry, index) => (
                <Cell key={entry.name} fill={chartColors[index % chartColors.length]} />
              ))}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </section>

      <section className="insight-panel">
        <span className="eyebrow">Timeline</span>
        <h3>Daily leads</h3>
        <ResponsiveContainer width="100%" height={220}>
          <LineChart data={dailyCounts}>
            <CartesianGrid strokeDasharray="3 3" vertical={false} />
            <XAxis dataKey="date" tick={{ fontSize: 11 }} />
            <YAxis allowDecimals={false} width={28} />
            <Tooltip />
            <Line dataKey="leads" stroke="#525ddc" strokeWidth={3} type="monotone" />
          </LineChart>
        </ResponsiveContainer>
      </section>

      <section className="insight-panel">
        <span className="eyebrow">Configuration</span>
        <h3>Finish demand</h3>
        <ResponsiveContainer width="100%" height={220}>
          <PieChart>
            <Pie
              data={finishCounts}
              dataKey="value"
              innerRadius={48}
              nameKey="name"
              outerRadius={82}
              paddingAngle={3}
            >
              {finishCounts.map((entry, index) => (
                <Cell key={entry.name} fill={chartColors[index % chartColors.length]} />
              ))}
            </Pie>
            <Tooltip />
          </PieChart>
        </ResponsiveContainer>
      </section>
    </div>
  );
}
