// frontend/src/components/ProductCard.tsx
import { ArrowRight } from "lucide-react";
import type { CSSProperties } from "react";
import { Link } from "react-router-dom";

import { ResponsiveProductImage } from "./ResponsiveProductImage";
import type { Product } from "../types/product";

type ProductCardProps = {
  onIntent?: (productId: string) => void;
  product: Product;
};

export function ProductCard({ onIntent, product }: ProductCardProps) {
  const handleIntent = () => onIntent?.(product.id);

  return (
    <Link
      className="product-card"
      to={`/products/${product.id}`}
      style={{ "--accent": product.accent } as CSSProperties}
      onFocus={handleIntent}
      onMouseEnter={handleIntent}
    >
      <div className="product-card-media">
        <ResponsiveProductImage
          src={product.hero_image}
          alt=""
          loading="lazy"
          sizes="(max-width: 700px) 100vw, (max-width: 980px) 50vw, 33vw"
        />
      </div>
      <div className="product-card-body">
        <span className="eyebrow">{product.category}</span>
        <h3>{product.name}</h3>
        <p>{product.tagline}</p>
        <div className="product-card-footer">
          <strong>${product.price}</strong>
          <span className="icon-link" aria-hidden="true">
            <ArrowRight size={18} />
          </span>
        </div>
      </div>
    </Link>
  );
}

// apps/web-vue/src/components/ProductCard.vue
<script setup lang="ts">
import type { Product } from "@lumadock/api-client";
import { ArrowRight } from "lucide-vue-next";
import type { CSSProperties } from "vue";

import ResponsiveProductImage from "./ResponsiveProductImage.vue";

const props = defineProps<{
  onIntent?: (productId: string) => void;
  product: Product;
}>();

const accentStyle = {
  "--accent": props.product.accent,
} as CSSProperties;

function handleIntent() {
  props.onIntent?.(props.product.id);
}
</script>

<template>
  <RouterLink
    class="product-card"
    :style="accentStyle"
    :to="`/products/${product.id}`"
    @focus="handleIntent"
    @pointerenter="handleIntent"
  >
    <div class="product-card-media">
      <ResponsiveProductImage
        :src="product.hero_image"
        :alt="`${product.name} product render`"
        loading="lazy"
        sizes="(max-width: 700px) 100vw, 33vw"
      />
    </div>
    <div class="product-card-body">
      <span class="eyebrow">{{ product.category }}</span>
      <h3>{{ product.name }}</h3>
      <p>{{ product.tagline }}</p>
      <div class="product-card-footer">
        <strong>${{ product.price }}</strong>
        <span class="icon-link" aria-hidden="true">
          <ArrowRight :size="16" />
        </span>
      </div>
    </div>
  </RouterLink>
</template>
