// frontend/src/components/ResponsiveProductImage.tsx
import type { ImgHTMLAttributes } from "react";

type ResponsiveProductImageProps = ImgHTMLAttributes<HTMLImageElement> & {
  src: string;
};

const lumadockHeroSources = [
  { src: "/assets/lumadock-hero-640.webp", width: 640 },
  { src: "/assets/lumadock-hero-960.webp", width: 960 },
  { src: "/assets/lumadock-hero-1280.webp", width: 1280 },
];

function buildSrcSet() {
  return lumadockHeroSources.map((source) => `${source.src} ${source.width}w`).join(", ");
}

export function ResponsiveProductImage({
  alt,
  decoding = "async",
  loading = "lazy",
  sizes = "(max-width: 700px) 100vw, 50vw",
  src,
  ...imageProps
}: ResponsiveProductImageProps) {
  if (src !== "/assets/lumadock-hero.png") {
    return <img alt={alt} decoding={decoding} loading={loading} src={src} {...imageProps} />;
  }

  return (
    <picture>
      <source srcSet={buildSrcSet()} sizes={sizes} type="image/webp" />
      <img alt={alt} decoding={decoding} loading={loading} src={src} {...imageProps} />
    </picture>
  );
}

// apps/web-vue/src/components/ResponsiveProductImage.vue
<script setup lang="ts">
defineProps<{
  alt: string;
  loading?: "eager" | "lazy";
  sizes?: string;
  src: string;
}>();
</script>

<template>
  <picture>
    <source
      srcset="
        /assets/lumadock-hero-640.webp   640w,
        /assets/lumadock-hero-960.webp   960w,
        /assets/lumadock-hero-1280.webp 1280w
      "
      type="image/webp"
      :sizes="sizes"
    />
    <img :src="src" :alt="alt" :loading="loading" :sizes="sizes" />
  </picture>
</template>
